### ISSUE TITLE
A question about density estimator

### ISSUE THREAD

**Issue by Italy2006** [Gavinwxy/DDFP#3]
After reading your paper, I have a question. Why not directly use Gaussian mixture Models to model the features output by the backbone network? which seems to be able to calculate the distribution of features and the corresponding perturbations. Why is it necessary to design a density estimator?

**Comment by gavinwxy** [comment]
I have several considerations:
1. Compared with direct fitting with GMM, normalizing-flow-based has better representational flexibility, which means, theoretically, its transformation and mappings on features allows more accurate estimation.
2. The fitting of conventional GMM relies on EM algorithm, in which the model needs to see all the features in all categories for the fitting. It is not desired in our work since we need online estimation along with segmentation training, while normalizing flow can be trained that way.
3. For the perturbation generation, it is quite convenient for normalizing flow since the gradient can be extracted directly from the density representation, while conventional GMM cannot do that. 

BTW I will publish the code ASAP, hopefully in Aug. Thanks for your interest.
